### ISSUE TITLE
Questions about implementation details

### ISSUE THREAD

**Issue by Angericky** [4DVLab/STCrowd#1]
Thanks for your efforts and the excellent dataset!
I have 2 following questions about the detection baseline:
 
1. This paper claimed that  fine-grained heatmap can do one-to-one assignment, so how much is the stride of the largest heamap?
Is it **4x** voxel size/pillar size?

2. Voxel size is set to [0.12m, 0.16m] and anchors are set to [0.57m, 0.6m] on x-axis and y-axis separately. Why are resolutions on x and y axis not the same?

**Comment by 4DVLab** [comment]
1. The grid size in heatmap is **2x** voxel size. 
2. the point cloud range is 0~30.72 and -20.48~20.28 for x and y axis(since we only use 180 range), I maintain the feature map to be 256*256 so that the voxel size is adjust as 0.12*0.16. As for anchor size, it is calculated from average bounding boxes size.

**Comment by Angericky** [comment]
Got it. Thanks for your fast reply!
